[invalid.py]
  [test_closed_frame]
    bug: 1761445
    expected: FAIL
