[invalid.py]
  expected:
    if (processor == "x86") and not debug: [OK, TIMEOUT]
  [test_params_descriptor_invalid_type[False\]]
    expected: FAIL

  [test_params_descriptor_invalid_type[SOME_STRING\]]
    expected: FAIL

  [test_params_descriptor_invalid_type[42\]]
    expected: FAIL

  [test_params_descriptor_invalid_type[descriptor3\]]
    expected: FAIL

  [test_params_descriptor_invalid_type[descriptor4\]]
    expected: FAIL

  [test_params_descriptor_invalid_type[descriptor5\]]
    expected: FAIL

  [test_params_descriptor_invalid_type[None\]]
    expected: FAIL

  [test_params_descriptor_invalid_type[descriptor7\]]
    expected: FAIL

  [test_params_descriptor_invalid_value[descriptor0\]]
    expected: FAIL

  [test_params_state_invalid_type[False\]]
    expected: FAIL

  [test_params_state_invalid_type[42\]]
    expected: FAIL

  [test_params_state_invalid_type[state2\]]
    expected: FAIL

  [test_params_state_invalid_type[state3\]]
    expected: FAIL

  [test_params_state_invalid_type[None\]]
    expected: FAIL

  [test_params_state_invalid_type[state5\]]
    expected: FAIL

  [test_params_state_invalid_value[Granted\]]
    expected: FAIL

  [test_params_origin_invalid_type[False\]]
    expected: FAIL

  [test_params_origin_invalid_type[42\]]
    expected: FAIL

  [test_params_origin_invalid_type[None\]]
    expected: FAIL

  [test_params_state_invalid_value[UNKNOWN\]]
    expected: FAIL

  [test_params_origin_invalid_type[user_context2\]]
    expected: FAIL

  [test_params_origin_invalid_type[user_context3\]]
    expected: FAIL
